---
name: tests

on: [push, pull_request]

jobs:
  template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Template
        run: |
          pip install cookiecutter
          cookiecutter --no-input .
          pwd
          ls -al pylate

  lint:
    needs: template
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Template
        run: |
          pip install cookiecutter
          cookiecutter --no-input .
          pwd
          ls -al pylate

      - name: Linting
        working-directory: "$HOME/work/pylate"
        run: |
          pwd
          ls -al
          pip install pre-commit
          pre-commit run --all-files

  test:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Template
        run: |
          pip install cookiecutter
          cookiecutter --no-input .
          pwd
          ls -al pylate

      - name: Install poetry
        run: |
          curl -sSL \
            "https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py" | python

      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        working-directory: "$HOME/work/pylate"
        run: |
          source "$HOME/pylate/.poetry/env"
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run tests
        working-directory: "$HOME/work/pylate"
        run: |
          source "$HOME/pylate/.poetry/env"
          poetry run pytest
