---
name: tests

on: [push, pull_request]

jobs:
  template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Template
        run: |
          pip install cookiecutter
          cookiecutter --no-input .
          pwd
          ls -al pylate

  lint:
    needs: template
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Template
        run: |
          pip install cookiecutter
          cookiecutter --no-input .
          pwd
          ls -al pylate

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          cd pylate
          poetry config virtualenvs.in-project true
          poetry install

      - name: black
        run: |
          cd pylate
          black

      - name: flake8
        run: |
          cd pylate
          flake8

      - name: mypy
        run: |
          cd pylate
          mypy

  test:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Template
        run: |
          pip install cookiecutter
          cookiecutter --no-input .
          pwd
          ls -al pylate

      - name: Install poetry
        run: |
          pip install poetry

      - name: Install dependencies
        run: |
          cd pylate
          poetry config virtualenvs.in-project true
          poetry install

      - name: Run tests
        run: |
          cd pylate
          poetry run pytest
